general:
  #sets debug mode on or off. Turn off if you do not want to see as much info on in the server console or log files
  debugMode: false
cannonLimits:
  #limits regarding how many cannons a player can build. set to false if you dont need to use it
  useLimits: false
  buildLimitA: 1
  buildLimitB: 100
tools:
  #the item a player needs to be holding to adjust the aim of a cannon. Default is none.
  ajust: '0:0'
  #the item used to autoaim a cannon. Default is clock
  autoaim: '347:0'
  #the item used to fire a cannon. Default is flint and steel. Not every cannon needs a FiringItem.
  firing: '259:0'
  #item used to rotate a cannon 90 degrees. Not implemented yet
  rotatingItem: '350:0'
database:
  #database implementation. Default is SQLite, can be changed to MySql if you change the driver.  
  username: bukkit
  password: walrus
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:{DIR}{NAME}.db