name: Cannons
main: at.pavlov.cannons.Cannons
version: 2.0.1
softdepend: [WorldEdit,ObsidianDestroyer,CreeperHeal]
author: DerPavlov
description: Fire block build cannons and smash your enemies

commands:
  cannons:
    description: Info how to use/build/adjust a cannon and to reload the plugin.

permissions:
  cannons.*:
    description: Gives single permissions for loading, adjusting, firing and recall help with cannons
    children:
      cannons.player.*: true
      cannons.admin.*: true
  
  cannons.player.*:
    description: Gives single permissions for loading, adjusting, firing and recall help with cannons
    children:
      cannons.player.command: true
      cannons.player.build: true
      cannons.player.load: true
      cannons.player.adjust: true
      cannons.player.fire: true
      cannons.player.autoaim: true
      cannons.player.tracking: true
      cannons.player.autoreload: true
      cannons.player.help: true
      cannons.player.reset: true
      cannons.player.redstone: true
      cannons.player.list: true
      cannons.projectile.default: true
  cannons.admin.*:
    description: Gives all admin rights
    children:
      cannons.admin.reload: true
      cannons.admin.reset: true
      cannons.admin.list: true

  cannons.player.command:
      description: Allows a player to use the help commands
      default: true
  cannons.player.build:
      description: Allows a player to build a cannon
      default: false
  cannons.player.load:
      description: Allows a player to load a cannon
      default: false
  cannons.player.fire:
      description: Allows a player to fire a cannon
      default: false
  cannons.player.adjust:
      description: Allows a player to adjust a cannon
      default: false
  cannons.player.autoaim:
      description: Allows a player to autoaim with a cannon
      default: false
  cannons.player.redstone:
      description: Allows a player to use redstone with a cannon
      default: false
  cannons.player.autoreload:
      description: Allows a player to use autoreload on a cannon
      default: false
  cannons.player.limitA:
      description: Maximum amount of cannons a player can place
      default: false
  cannons.player.limitB:
      description: Maximum amount of cannons a player can place
      default: false
  cannons.player.limit:
      description: Set the of cannons a player can build as number e.g. limit.5
      default: false
  cannons.player.help:
      description: Allows a player to request help with a cannon
      default: false
  cannons.player.reset:
      description: Allows a player to delete all of his build cannons.
      default: false
  cannons.player.redstone:
      description: Allows a player to place redstone torch under a cannon
      default: false
  cannons.player.list:
      description: Allows a player to request a list of all his cannons
      default: false
  cannons.projectile.default:
      description: Allows a player to use default projectiles
      default: false
  cannons.admin.reload:
      description: Allows an admin to reload the config
      default: op
  cannons.admin.reset:
      description: Allows an admin to delete all cannon of a player in the database
      default: op
  cannons.admin.list:
      description: Allows an admin to list all cannon of a player
      default: op
